// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AVInputOpenResponseMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AVInputOpenResponseMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_AVInputOpenResponseMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_AVInputOpenResponseMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AVInputOpenResponseMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AVInputOpenResponseMessage_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace messages {
class AVInputOpenResponse;
struct AVInputOpenResponseDefaultTypeInternal;
extern AVInputOpenResponseDefaultTypeInternal _AVInputOpenResponse_default_instance_;
}  // namespace messages
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::messages::AVInputOpenResponse* Arena::CreateMaybeMessage<::f1x::aasdk::proto::messages::AVInputOpenResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace messages {

// ===================================================================

class AVInputOpenResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.messages.AVInputOpenResponse) */ {
 public:
  inline AVInputOpenResponse() : AVInputOpenResponse(nullptr) {}
  ~AVInputOpenResponse() override;
  explicit PROTOBUF_CONSTEXPR AVInputOpenResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AVInputOpenResponse(const AVInputOpenResponse& from);
  AVInputOpenResponse(AVInputOpenResponse&& from) noexcept
    : AVInputOpenResponse() {
    *this = ::std::move(from);
  }

  inline AVInputOpenResponse& operator=(const AVInputOpenResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AVInputOpenResponse& operator=(AVInputOpenResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AVInputOpenResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AVInputOpenResponse* internal_default_instance() {
    return reinterpret_cast<const AVInputOpenResponse*>(
               &_AVInputOpenResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AVInputOpenResponse& a, AVInputOpenResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AVInputOpenResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AVInputOpenResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AVInputOpenResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AVInputOpenResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AVInputOpenResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AVInputOpenResponse& from) {
    AVInputOpenResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AVInputOpenResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.messages.AVInputOpenResponse";
  }
  protected:
  explicit AVInputOpenResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // required int32 session = 1;
  bool has_session() const;
  private:
  bool _internal_has_session() const;
  public:
  void clear_session();
  int32_t session() const;
  void set_session(int32_t value);
  private:
  int32_t _internal_session() const;
  void _internal_set_session(int32_t value);
  public:

  // required uint32 value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  uint32_t value() const;
  void set_value(uint32_t value);
  private:
  uint32_t _internal_value() const;
  void _internal_set_value(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.messages.AVInputOpenResponse)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int32_t session_;
    uint32_t value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AVInputOpenResponseMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AVInputOpenResponse

// required int32 session = 1;
inline bool AVInputOpenResponse::_internal_has_session() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool AVInputOpenResponse::has_session() const {
  return _internal_has_session();
}
inline void AVInputOpenResponse::clear_session() {
  _impl_.session_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t AVInputOpenResponse::_internal_session() const {
  return _impl_.session_;
}
inline int32_t AVInputOpenResponse::session() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.messages.AVInputOpenResponse.session)
  return _internal_session();
}
inline void AVInputOpenResponse::_internal_set_session(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.session_ = value;
}
inline void AVInputOpenResponse::set_session(int32_t value) {
  _internal_set_session(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.messages.AVInputOpenResponse.session)
}

// required uint32 value = 2;
inline bool AVInputOpenResponse::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool AVInputOpenResponse::has_value() const {
  return _internal_has_value();
}
inline void AVInputOpenResponse::clear_value() {
  _impl_.value_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t AVInputOpenResponse::_internal_value() const {
  return _impl_.value_;
}
inline uint32_t AVInputOpenResponse::value() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.messages.AVInputOpenResponse.value)
  return _internal_value();
}
inline void AVInputOpenResponse::_internal_set_value(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_ = value;
}
inline void AVInputOpenResponse::set_value(uint32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.messages.AVInputOpenResponse.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_AVInputOpenResponseMessage_2eproto
