// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AVInputChannelData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_AVInputChannelData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_AVInputChannelData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "AVStreamTypeEnum.pb.h"
#include "AudioConfigData.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_AVInputChannelData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_AVInputChannelData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_AVInputChannelData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class AVInputChannel;
struct AVInputChannelDefaultTypeInternal;
extern AVInputChannelDefaultTypeInternal _AVInputChannel_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::AVInputChannel* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::AVInputChannel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class AVInputChannel final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.AVInputChannel) */ {
 public:
  inline AVInputChannel() : AVInputChannel(nullptr) {}
  ~AVInputChannel() override;
  explicit PROTOBUF_CONSTEXPR AVInputChannel(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AVInputChannel(const AVInputChannel& from);
  AVInputChannel(AVInputChannel&& from) noexcept
    : AVInputChannel() {
    *this = ::std::move(from);
  }

  inline AVInputChannel& operator=(const AVInputChannel& from) {
    CopyFrom(from);
    return *this;
  }
  inline AVInputChannel& operator=(AVInputChannel&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AVInputChannel& default_instance() {
    return *internal_default_instance();
  }
  static inline const AVInputChannel* internal_default_instance() {
    return reinterpret_cast<const AVInputChannel*>(
               &_AVInputChannel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AVInputChannel& a, AVInputChannel& b) {
    a.Swap(&b);
  }
  inline void Swap(AVInputChannel* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AVInputChannel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AVInputChannel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AVInputChannel>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AVInputChannel& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AVInputChannel& from) {
    AVInputChannel::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AVInputChannel* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.AVInputChannel";
  }
  protected:
  explicit AVInputChannel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAudioConfigFieldNumber = 2,
    kStreamTypeFieldNumber = 1,
    kAvailableWhileInCallFieldNumber = 3,
  };
  // .f1x.aasdk.proto.data.AudioConfig audio_config = 2;
  bool has_audio_config() const;
  private:
  bool _internal_has_audio_config() const;
  public:
  void clear_audio_config();
  const ::f1x::aasdk::proto::data::AudioConfig& audio_config() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::AudioConfig* release_audio_config();
  ::f1x::aasdk::proto::data::AudioConfig* mutable_audio_config();
  void set_allocated_audio_config(::f1x::aasdk::proto::data::AudioConfig* audio_config);
  private:
  const ::f1x::aasdk::proto::data::AudioConfig& _internal_audio_config() const;
  ::f1x::aasdk::proto::data::AudioConfig* _internal_mutable_audio_config();
  public:
  void unsafe_arena_set_allocated_audio_config(
      ::f1x::aasdk::proto::data::AudioConfig* audio_config);
  ::f1x::aasdk::proto::data::AudioConfig* unsafe_arena_release_audio_config();

  // .f1x.aasdk.proto.enums.AVStreamType.Enum stream_type = 1;
  void clear_stream_type();
  ::f1x::aasdk::proto::enums::AVStreamType_Enum stream_type() const;
  void set_stream_type(::f1x::aasdk::proto::enums::AVStreamType_Enum value);
  private:
  ::f1x::aasdk::proto::enums::AVStreamType_Enum _internal_stream_type() const;
  void _internal_set_stream_type(::f1x::aasdk::proto::enums::AVStreamType_Enum value);
  public:

  // bool available_while_in_call = 3;
  void clear_available_while_in_call();
  bool available_while_in_call() const;
  void set_available_while_in_call(bool value);
  private:
  bool _internal_available_while_in_call() const;
  void _internal_set_available_while_in_call(bool value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.AVInputChannel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::f1x::aasdk::proto::data::AudioConfig* audio_config_;
    int stream_type_;
    bool available_while_in_call_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AVInputChannelData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AVInputChannel

// .f1x.aasdk.proto.enums.AVStreamType.Enum stream_type = 1;
inline void AVInputChannel::clear_stream_type() {
  _impl_.stream_type_ = 0;
}
inline ::f1x::aasdk::proto::enums::AVStreamType_Enum AVInputChannel::_internal_stream_type() const {
  return static_cast< ::f1x::aasdk::proto::enums::AVStreamType_Enum >(_impl_.stream_type_);
}
inline ::f1x::aasdk::proto::enums::AVStreamType_Enum AVInputChannel::stream_type() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.AVInputChannel.stream_type)
  return _internal_stream_type();
}
inline void AVInputChannel::_internal_set_stream_type(::f1x::aasdk::proto::enums::AVStreamType_Enum value) {
  
  _impl_.stream_type_ = value;
}
inline void AVInputChannel::set_stream_type(::f1x::aasdk::proto::enums::AVStreamType_Enum value) {
  _internal_set_stream_type(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.AVInputChannel.stream_type)
}

// .f1x.aasdk.proto.data.AudioConfig audio_config = 2;
inline bool AVInputChannel::_internal_has_audio_config() const {
  return this != internal_default_instance() && _impl_.audio_config_ != nullptr;
}
inline bool AVInputChannel::has_audio_config() const {
  return _internal_has_audio_config();
}
inline const ::f1x::aasdk::proto::data::AudioConfig& AVInputChannel::_internal_audio_config() const {
  const ::f1x::aasdk::proto::data::AudioConfig* p = _impl_.audio_config_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::AudioConfig&>(
      ::f1x::aasdk::proto::data::_AudioConfig_default_instance_);
}
inline const ::f1x::aasdk::proto::data::AudioConfig& AVInputChannel::audio_config() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.AVInputChannel.audio_config)
  return _internal_audio_config();
}
inline void AVInputChannel::unsafe_arena_set_allocated_audio_config(
    ::f1x::aasdk::proto::data::AudioConfig* audio_config) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.audio_config_);
  }
  _impl_.audio_config_ = audio_config;
  if (audio_config) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.AVInputChannel.audio_config)
}
inline ::f1x::aasdk::proto::data::AudioConfig* AVInputChannel::release_audio_config() {
  
  ::f1x::aasdk::proto::data::AudioConfig* temp = _impl_.audio_config_;
  _impl_.audio_config_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::AudioConfig* AVInputChannel::unsafe_arena_release_audio_config() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.AVInputChannel.audio_config)
  
  ::f1x::aasdk::proto::data::AudioConfig* temp = _impl_.audio_config_;
  _impl_.audio_config_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::AudioConfig* AVInputChannel::_internal_mutable_audio_config() {
  
  if (_impl_.audio_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::AudioConfig>(GetArenaForAllocation());
    _impl_.audio_config_ = p;
  }
  return _impl_.audio_config_;
}
inline ::f1x::aasdk::proto::data::AudioConfig* AVInputChannel::mutable_audio_config() {
  ::f1x::aasdk::proto::data::AudioConfig* _msg = _internal_mutable_audio_config();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.AVInputChannel.audio_config)
  return _msg;
}
inline void AVInputChannel::set_allocated_audio_config(::f1x::aasdk::proto::data::AudioConfig* audio_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.audio_config_);
  }
  if (audio_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(audio_config));
    if (message_arena != submessage_arena) {
      audio_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, audio_config, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.audio_config_ = audio_config;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.AVInputChannel.audio_config)
}

// bool available_while_in_call = 3;
inline void AVInputChannel::clear_available_while_in_call() {
  _impl_.available_while_in_call_ = false;
}
inline bool AVInputChannel::_internal_available_while_in_call() const {
  return _impl_.available_while_in_call_;
}
inline bool AVInputChannel::available_while_in_call() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.AVInputChannel.available_while_in_call)
  return _internal_available_while_in_call();
}
inline void AVInputChannel::_internal_set_available_while_in_call(bool value) {
  
  _impl_.available_while_in_call_ = value;
}
inline void AVInputChannel::set_available_while_in_call(bool value) {
  _internal_set_available_while_in_call(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.AVInputChannel.available_while_in_call)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_AVInputChannelData_2eproto
