// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BluetoothChannelData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BluetoothChannelData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BluetoothChannelData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BluetoothPairingMethodEnum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BluetoothChannelData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BluetoothChannelData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BluetoothChannelData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class BluetoothChannel;
struct BluetoothChannelDefaultTypeInternal;
extern BluetoothChannelDefaultTypeInternal _BluetoothChannel_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::BluetoothChannel* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::BluetoothChannel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class BluetoothChannel final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.BluetoothChannel) */ {
 public:
  inline BluetoothChannel() : BluetoothChannel(nullptr) {}
  ~BluetoothChannel() override;
  explicit PROTOBUF_CONSTEXPR BluetoothChannel(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BluetoothChannel(const BluetoothChannel& from);
  BluetoothChannel(BluetoothChannel&& from) noexcept
    : BluetoothChannel() {
    *this = ::std::move(from);
  }

  inline BluetoothChannel& operator=(const BluetoothChannel& from) {
    CopyFrom(from);
    return *this;
  }
  inline BluetoothChannel& operator=(BluetoothChannel&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BluetoothChannel& default_instance() {
    return *internal_default_instance();
  }
  static inline const BluetoothChannel* internal_default_instance() {
    return reinterpret_cast<const BluetoothChannel*>(
               &_BluetoothChannel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BluetoothChannel& a, BluetoothChannel& b) {
    a.Swap(&b);
  }
  inline void Swap(BluetoothChannel* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BluetoothChannel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BluetoothChannel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BluetoothChannel>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BluetoothChannel& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BluetoothChannel& from) {
    BluetoothChannel::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BluetoothChannel* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.BluetoothChannel";
  }
  protected:
  explicit BluetoothChannel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSupportedPairingMethodsFieldNumber = 2,
    kAdapterAddressFieldNumber = 1,
  };
  // repeated .f1x.aasdk.proto.enums.BluetoothPairingMethod.Enum supported_pairing_methods = 2;
  int supported_pairing_methods_size() const;
  private:
  int _internal_supported_pairing_methods_size() const;
  public:
  void clear_supported_pairing_methods();
  private:
  ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum _internal_supported_pairing_methods(int index) const;
  void _internal_add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_supported_pairing_methods();
  public:
  ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum supported_pairing_methods(int index) const;
  void set_supported_pairing_methods(int index, ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value);
  void add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& supported_pairing_methods() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_supported_pairing_methods();

  // string adapter_address = 1;
  void clear_adapter_address();
  const std::string& adapter_address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_adapter_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_adapter_address();
  PROTOBUF_NODISCARD std::string* release_adapter_address();
  void set_allocated_adapter_address(std::string* adapter_address);
  private:
  const std::string& _internal_adapter_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_adapter_address(const std::string& value);
  std::string* _internal_mutable_adapter_address();
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.BluetoothChannel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> supported_pairing_methods_;
    mutable std::atomic<int> _supported_pairing_methods_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr adapter_address_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BluetoothChannelData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BluetoothChannel

// string adapter_address = 1;
inline void BluetoothChannel::clear_adapter_address() {
  _impl_.adapter_address_.ClearToEmpty();
}
inline const std::string& BluetoothChannel::adapter_address() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
  return _internal_adapter_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BluetoothChannel::set_adapter_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.adapter_address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}
inline std::string* BluetoothChannel::mutable_adapter_address() {
  std::string* _s = _internal_mutable_adapter_address();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
  return _s;
}
inline const std::string& BluetoothChannel::_internal_adapter_address() const {
  return _impl_.adapter_address_.Get();
}
inline void BluetoothChannel::_internal_set_adapter_address(const std::string& value) {
  
  _impl_.adapter_address_.Set(value, GetArenaForAllocation());
}
inline std::string* BluetoothChannel::_internal_mutable_adapter_address() {
  
  return _impl_.adapter_address_.Mutable(GetArenaForAllocation());
}
inline std::string* BluetoothChannel::release_adapter_address() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
  return _impl_.adapter_address_.Release();
}
inline void BluetoothChannel::set_allocated_adapter_address(std::string* adapter_address) {
  if (adapter_address != nullptr) {
    
  } else {
    
  }
  _impl_.adapter_address_.SetAllocated(adapter_address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.adapter_address_.IsDefault()) {
    _impl_.adapter_address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.BluetoothChannel.adapter_address)
}

// repeated .f1x.aasdk.proto.enums.BluetoothPairingMethod.Enum supported_pairing_methods = 2;
inline int BluetoothChannel::_internal_supported_pairing_methods_size() const {
  return _impl_.supported_pairing_methods_.size();
}
inline int BluetoothChannel::supported_pairing_methods_size() const {
  return _internal_supported_pairing_methods_size();
}
inline void BluetoothChannel::clear_supported_pairing_methods() {
  _impl_.supported_pairing_methods_.Clear();
}
inline ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum BluetoothChannel::_internal_supported_pairing_methods(int index) const {
  return static_cast< ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum >(_impl_.supported_pairing_methods_.Get(index));
}
inline ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum BluetoothChannel::supported_pairing_methods(int index) const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
  return _internal_supported_pairing_methods(index);
}
inline void BluetoothChannel::set_supported_pairing_methods(int index, ::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value) {
  _impl_.supported_pairing_methods_.Set(index, value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
}
inline void BluetoothChannel::_internal_add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value) {
  _impl_.supported_pairing_methods_.Add(value);
}
inline void BluetoothChannel::add_supported_pairing_methods(::f1x::aasdk::proto::enums::BluetoothPairingMethod_Enum value) {
  _internal_add_supported_pairing_methods(value);
  // @@protoc_insertion_point(field_add:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
BluetoothChannel::supported_pairing_methods() const {
  // @@protoc_insertion_point(field_list:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
  return _impl_.supported_pairing_methods_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
BluetoothChannel::_internal_mutable_supported_pairing_methods() {
  return &_impl_.supported_pairing_methods_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
BluetoothChannel::mutable_supported_pairing_methods() {
  // @@protoc_insertion_point(field_mutable_list:f1x.aasdk.proto.data.BluetoothChannel.supported_pairing_methods)
  return _internal_mutable_supported_pairing_methods();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BluetoothChannelData_2eproto
