// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChannelDescriptorData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ChannelDescriptorData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ChannelDescriptorData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "SensorChannelData.pb.h"
#include "AVChannelData.pb.h"
#include "InputChannelData.pb.h"
#include "AVInputChannelData.pb.h"
#include "BluetoothChannelData.pb.h"
#include "NavigationChannelData.pb.h"
#include "VendorExtensionChannelData.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ChannelDescriptorData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ChannelDescriptorData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ChannelDescriptorData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class ChannelDescriptor;
struct ChannelDescriptorDefaultTypeInternal;
extern ChannelDescriptorDefaultTypeInternal _ChannelDescriptor_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::ChannelDescriptor* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::ChannelDescriptor>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class ChannelDescriptor final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.ChannelDescriptor) */ {
 public:
  inline ChannelDescriptor() : ChannelDescriptor(nullptr) {}
  ~ChannelDescriptor() override;
  explicit PROTOBUF_CONSTEXPR ChannelDescriptor(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChannelDescriptor(const ChannelDescriptor& from);
  ChannelDescriptor(ChannelDescriptor&& from) noexcept
    : ChannelDescriptor() {
    *this = ::std::move(from);
  }

  inline ChannelDescriptor& operator=(const ChannelDescriptor& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChannelDescriptor& operator=(ChannelDescriptor&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChannelDescriptor& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChannelDescriptor* internal_default_instance() {
    return reinterpret_cast<const ChannelDescriptor*>(
               &_ChannelDescriptor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChannelDescriptor& a, ChannelDescriptor& b) {
    a.Swap(&b);
  }
  inline void Swap(ChannelDescriptor* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChannelDescriptor* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChannelDescriptor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChannelDescriptor>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChannelDescriptor& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChannelDescriptor& from) {
    ChannelDescriptor::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChannelDescriptor* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.ChannelDescriptor";
  }
  protected:
  explicit ChannelDescriptor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSensorChannelFieldNumber = 2,
    kAvChannelFieldNumber = 3,
    kInputChannelFieldNumber = 4,
    kAvInputChannelFieldNumber = 5,
    kBluetoothChannelFieldNumber = 6,
    kNavigationChannelFieldNumber = 8,
    kVendorExtensionChannelFieldNumber = 12,
    kChannelIdFieldNumber = 1,
  };
  // .f1x.aasdk.proto.data.SensorChannel sensor_channel = 2;
  bool has_sensor_channel() const;
  private:
  bool _internal_has_sensor_channel() const;
  public:
  void clear_sensor_channel();
  const ::f1x::aasdk::proto::data::SensorChannel& sensor_channel() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::SensorChannel* release_sensor_channel();
  ::f1x::aasdk::proto::data::SensorChannel* mutable_sensor_channel();
  void set_allocated_sensor_channel(::f1x::aasdk::proto::data::SensorChannel* sensor_channel);
  private:
  const ::f1x::aasdk::proto::data::SensorChannel& _internal_sensor_channel() const;
  ::f1x::aasdk::proto::data::SensorChannel* _internal_mutable_sensor_channel();
  public:
  void unsafe_arena_set_allocated_sensor_channel(
      ::f1x::aasdk::proto::data::SensorChannel* sensor_channel);
  ::f1x::aasdk::proto::data::SensorChannel* unsafe_arena_release_sensor_channel();

  // .f1x.aasdk.proto.data.AVChannel av_channel = 3;
  bool has_av_channel() const;
  private:
  bool _internal_has_av_channel() const;
  public:
  void clear_av_channel();
  const ::f1x::aasdk::proto::data::AVChannel& av_channel() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::AVChannel* release_av_channel();
  ::f1x::aasdk::proto::data::AVChannel* mutable_av_channel();
  void set_allocated_av_channel(::f1x::aasdk::proto::data::AVChannel* av_channel);
  private:
  const ::f1x::aasdk::proto::data::AVChannel& _internal_av_channel() const;
  ::f1x::aasdk::proto::data::AVChannel* _internal_mutable_av_channel();
  public:
  void unsafe_arena_set_allocated_av_channel(
      ::f1x::aasdk::proto::data::AVChannel* av_channel);
  ::f1x::aasdk::proto::data::AVChannel* unsafe_arena_release_av_channel();

  // .f1x.aasdk.proto.data.InputChannel input_channel = 4;
  bool has_input_channel() const;
  private:
  bool _internal_has_input_channel() const;
  public:
  void clear_input_channel();
  const ::f1x::aasdk::proto::data::InputChannel& input_channel() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::InputChannel* release_input_channel();
  ::f1x::aasdk::proto::data::InputChannel* mutable_input_channel();
  void set_allocated_input_channel(::f1x::aasdk::proto::data::InputChannel* input_channel);
  private:
  const ::f1x::aasdk::proto::data::InputChannel& _internal_input_channel() const;
  ::f1x::aasdk::proto::data::InputChannel* _internal_mutable_input_channel();
  public:
  void unsafe_arena_set_allocated_input_channel(
      ::f1x::aasdk::proto::data::InputChannel* input_channel);
  ::f1x::aasdk::proto::data::InputChannel* unsafe_arena_release_input_channel();

  // .f1x.aasdk.proto.data.AVInputChannel av_input_channel = 5;
  bool has_av_input_channel() const;
  private:
  bool _internal_has_av_input_channel() const;
  public:
  void clear_av_input_channel();
  const ::f1x::aasdk::proto::data::AVInputChannel& av_input_channel() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::AVInputChannel* release_av_input_channel();
  ::f1x::aasdk::proto::data::AVInputChannel* mutable_av_input_channel();
  void set_allocated_av_input_channel(::f1x::aasdk::proto::data::AVInputChannel* av_input_channel);
  private:
  const ::f1x::aasdk::proto::data::AVInputChannel& _internal_av_input_channel() const;
  ::f1x::aasdk::proto::data::AVInputChannel* _internal_mutable_av_input_channel();
  public:
  void unsafe_arena_set_allocated_av_input_channel(
      ::f1x::aasdk::proto::data::AVInputChannel* av_input_channel);
  ::f1x::aasdk::proto::data::AVInputChannel* unsafe_arena_release_av_input_channel();

  // .f1x.aasdk.proto.data.BluetoothChannel bluetooth_channel = 6;
  bool has_bluetooth_channel() const;
  private:
  bool _internal_has_bluetooth_channel() const;
  public:
  void clear_bluetooth_channel();
  const ::f1x::aasdk::proto::data::BluetoothChannel& bluetooth_channel() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::BluetoothChannel* release_bluetooth_channel();
  ::f1x::aasdk::proto::data::BluetoothChannel* mutable_bluetooth_channel();
  void set_allocated_bluetooth_channel(::f1x::aasdk::proto::data::BluetoothChannel* bluetooth_channel);
  private:
  const ::f1x::aasdk::proto::data::BluetoothChannel& _internal_bluetooth_channel() const;
  ::f1x::aasdk::proto::data::BluetoothChannel* _internal_mutable_bluetooth_channel();
  public:
  void unsafe_arena_set_allocated_bluetooth_channel(
      ::f1x::aasdk::proto::data::BluetoothChannel* bluetooth_channel);
  ::f1x::aasdk::proto::data::BluetoothChannel* unsafe_arena_release_bluetooth_channel();

  // .f1x.aasdk.proto.data.NavigationChannel navigation_channel = 8;
  bool has_navigation_channel() const;
  private:
  bool _internal_has_navigation_channel() const;
  public:
  void clear_navigation_channel();
  const ::f1x::aasdk::proto::data::NavigationChannel& navigation_channel() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::NavigationChannel* release_navigation_channel();
  ::f1x::aasdk::proto::data::NavigationChannel* mutable_navigation_channel();
  void set_allocated_navigation_channel(::f1x::aasdk::proto::data::NavigationChannel* navigation_channel);
  private:
  const ::f1x::aasdk::proto::data::NavigationChannel& _internal_navigation_channel() const;
  ::f1x::aasdk::proto::data::NavigationChannel* _internal_mutable_navigation_channel();
  public:
  void unsafe_arena_set_allocated_navigation_channel(
      ::f1x::aasdk::proto::data::NavigationChannel* navigation_channel);
  ::f1x::aasdk::proto::data::NavigationChannel* unsafe_arena_release_navigation_channel();

  // .f1x.aasdk.proto.data.VendorExtensionChannel vendor_extension_channel = 12;
  bool has_vendor_extension_channel() const;
  private:
  bool _internal_has_vendor_extension_channel() const;
  public:
  void clear_vendor_extension_channel();
  const ::f1x::aasdk::proto::data::VendorExtensionChannel& vendor_extension_channel() const;
  PROTOBUF_NODISCARD ::f1x::aasdk::proto::data::VendorExtensionChannel* release_vendor_extension_channel();
  ::f1x::aasdk::proto::data::VendorExtensionChannel* mutable_vendor_extension_channel();
  void set_allocated_vendor_extension_channel(::f1x::aasdk::proto::data::VendorExtensionChannel* vendor_extension_channel);
  private:
  const ::f1x::aasdk::proto::data::VendorExtensionChannel& _internal_vendor_extension_channel() const;
  ::f1x::aasdk::proto::data::VendorExtensionChannel* _internal_mutable_vendor_extension_channel();
  public:
  void unsafe_arena_set_allocated_vendor_extension_channel(
      ::f1x::aasdk::proto::data::VendorExtensionChannel* vendor_extension_channel);
  ::f1x::aasdk::proto::data::VendorExtensionChannel* unsafe_arena_release_vendor_extension_channel();

  // uint32 channel_id = 1;
  void clear_channel_id();
  uint32_t channel_id() const;
  void set_channel_id(uint32_t value);
  private:
  uint32_t _internal_channel_id() const;
  void _internal_set_channel_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.ChannelDescriptor)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::f1x::aasdk::proto::data::SensorChannel* sensor_channel_;
    ::f1x::aasdk::proto::data::AVChannel* av_channel_;
    ::f1x::aasdk::proto::data::InputChannel* input_channel_;
    ::f1x::aasdk::proto::data::AVInputChannel* av_input_channel_;
    ::f1x::aasdk::proto::data::BluetoothChannel* bluetooth_channel_;
    ::f1x::aasdk::proto::data::NavigationChannel* navigation_channel_;
    ::f1x::aasdk::proto::data::VendorExtensionChannel* vendor_extension_channel_;
    uint32_t channel_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ChannelDescriptorData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChannelDescriptor

// uint32 channel_id = 1;
inline void ChannelDescriptor::clear_channel_id() {
  _impl_.channel_id_ = 0u;
}
inline uint32_t ChannelDescriptor::_internal_channel_id() const {
  return _impl_.channel_id_;
}
inline uint32_t ChannelDescriptor::channel_id() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.channel_id)
  return _internal_channel_id();
}
inline void ChannelDescriptor::_internal_set_channel_id(uint32_t value) {
  
  _impl_.channel_id_ = value;
}
inline void ChannelDescriptor::set_channel_id(uint32_t value) {
  _internal_set_channel_id(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.ChannelDescriptor.channel_id)
}

// .f1x.aasdk.proto.data.SensorChannel sensor_channel = 2;
inline bool ChannelDescriptor::_internal_has_sensor_channel() const {
  return this != internal_default_instance() && _impl_.sensor_channel_ != nullptr;
}
inline bool ChannelDescriptor::has_sensor_channel() const {
  return _internal_has_sensor_channel();
}
inline const ::f1x::aasdk::proto::data::SensorChannel& ChannelDescriptor::_internal_sensor_channel() const {
  const ::f1x::aasdk::proto::data::SensorChannel* p = _impl_.sensor_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::SensorChannel&>(
      ::f1x::aasdk::proto::data::_SensorChannel_default_instance_);
}
inline const ::f1x::aasdk::proto::data::SensorChannel& ChannelDescriptor::sensor_channel() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.sensor_channel)
  return _internal_sensor_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_sensor_channel(
    ::f1x::aasdk::proto::data::SensorChannel* sensor_channel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.sensor_channel_);
  }
  _impl_.sensor_channel_ = sensor_channel;
  if (sensor_channel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.sensor_channel)
}
inline ::f1x::aasdk::proto::data::SensorChannel* ChannelDescriptor::release_sensor_channel() {
  
  ::f1x::aasdk::proto::data::SensorChannel* temp = _impl_.sensor_channel_;
  _impl_.sensor_channel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::SensorChannel* ChannelDescriptor::unsafe_arena_release_sensor_channel() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.ChannelDescriptor.sensor_channel)
  
  ::f1x::aasdk::proto::data::SensorChannel* temp = _impl_.sensor_channel_;
  _impl_.sensor_channel_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::SensorChannel* ChannelDescriptor::_internal_mutable_sensor_channel() {
  
  if (_impl_.sensor_channel_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::SensorChannel>(GetArenaForAllocation());
    _impl_.sensor_channel_ = p;
  }
  return _impl_.sensor_channel_;
}
inline ::f1x::aasdk::proto::data::SensorChannel* ChannelDescriptor::mutable_sensor_channel() {
  ::f1x::aasdk::proto::data::SensorChannel* _msg = _internal_mutable_sensor_channel();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.ChannelDescriptor.sensor_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_sensor_channel(::f1x::aasdk::proto::data::SensorChannel* sensor_channel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.sensor_channel_);
  }
  if (sensor_channel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sensor_channel));
    if (message_arena != submessage_arena) {
      sensor_channel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sensor_channel, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.sensor_channel_ = sensor_channel;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.sensor_channel)
}

// .f1x.aasdk.proto.data.AVChannel av_channel = 3;
inline bool ChannelDescriptor::_internal_has_av_channel() const {
  return this != internal_default_instance() && _impl_.av_channel_ != nullptr;
}
inline bool ChannelDescriptor::has_av_channel() const {
  return _internal_has_av_channel();
}
inline const ::f1x::aasdk::proto::data::AVChannel& ChannelDescriptor::_internal_av_channel() const {
  const ::f1x::aasdk::proto::data::AVChannel* p = _impl_.av_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::AVChannel&>(
      ::f1x::aasdk::proto::data::_AVChannel_default_instance_);
}
inline const ::f1x::aasdk::proto::data::AVChannel& ChannelDescriptor::av_channel() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.av_channel)
  return _internal_av_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_av_channel(
    ::f1x::aasdk::proto::data::AVChannel* av_channel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.av_channel_);
  }
  _impl_.av_channel_ = av_channel;
  if (av_channel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.av_channel)
}
inline ::f1x::aasdk::proto::data::AVChannel* ChannelDescriptor::release_av_channel() {
  
  ::f1x::aasdk::proto::data::AVChannel* temp = _impl_.av_channel_;
  _impl_.av_channel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::AVChannel* ChannelDescriptor::unsafe_arena_release_av_channel() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.ChannelDescriptor.av_channel)
  
  ::f1x::aasdk::proto::data::AVChannel* temp = _impl_.av_channel_;
  _impl_.av_channel_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::AVChannel* ChannelDescriptor::_internal_mutable_av_channel() {
  
  if (_impl_.av_channel_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::AVChannel>(GetArenaForAllocation());
    _impl_.av_channel_ = p;
  }
  return _impl_.av_channel_;
}
inline ::f1x::aasdk::proto::data::AVChannel* ChannelDescriptor::mutable_av_channel() {
  ::f1x::aasdk::proto::data::AVChannel* _msg = _internal_mutable_av_channel();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.ChannelDescriptor.av_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_av_channel(::f1x::aasdk::proto::data::AVChannel* av_channel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.av_channel_);
  }
  if (av_channel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(av_channel));
    if (message_arena != submessage_arena) {
      av_channel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, av_channel, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.av_channel_ = av_channel;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.av_channel)
}

// .f1x.aasdk.proto.data.InputChannel input_channel = 4;
inline bool ChannelDescriptor::_internal_has_input_channel() const {
  return this != internal_default_instance() && _impl_.input_channel_ != nullptr;
}
inline bool ChannelDescriptor::has_input_channel() const {
  return _internal_has_input_channel();
}
inline const ::f1x::aasdk::proto::data::InputChannel& ChannelDescriptor::_internal_input_channel() const {
  const ::f1x::aasdk::proto::data::InputChannel* p = _impl_.input_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::InputChannel&>(
      ::f1x::aasdk::proto::data::_InputChannel_default_instance_);
}
inline const ::f1x::aasdk::proto::data::InputChannel& ChannelDescriptor::input_channel() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.input_channel)
  return _internal_input_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_input_channel(
    ::f1x::aasdk::proto::data::InputChannel* input_channel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.input_channel_);
  }
  _impl_.input_channel_ = input_channel;
  if (input_channel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.input_channel)
}
inline ::f1x::aasdk::proto::data::InputChannel* ChannelDescriptor::release_input_channel() {
  
  ::f1x::aasdk::proto::data::InputChannel* temp = _impl_.input_channel_;
  _impl_.input_channel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::InputChannel* ChannelDescriptor::unsafe_arena_release_input_channel() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.ChannelDescriptor.input_channel)
  
  ::f1x::aasdk::proto::data::InputChannel* temp = _impl_.input_channel_;
  _impl_.input_channel_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::InputChannel* ChannelDescriptor::_internal_mutable_input_channel() {
  
  if (_impl_.input_channel_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::InputChannel>(GetArenaForAllocation());
    _impl_.input_channel_ = p;
  }
  return _impl_.input_channel_;
}
inline ::f1x::aasdk::proto::data::InputChannel* ChannelDescriptor::mutable_input_channel() {
  ::f1x::aasdk::proto::data::InputChannel* _msg = _internal_mutable_input_channel();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.ChannelDescriptor.input_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_input_channel(::f1x::aasdk::proto::data::InputChannel* input_channel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.input_channel_);
  }
  if (input_channel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(input_channel));
    if (message_arena != submessage_arena) {
      input_channel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, input_channel, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.input_channel_ = input_channel;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.input_channel)
}

// .f1x.aasdk.proto.data.AVInputChannel av_input_channel = 5;
inline bool ChannelDescriptor::_internal_has_av_input_channel() const {
  return this != internal_default_instance() && _impl_.av_input_channel_ != nullptr;
}
inline bool ChannelDescriptor::has_av_input_channel() const {
  return _internal_has_av_input_channel();
}
inline const ::f1x::aasdk::proto::data::AVInputChannel& ChannelDescriptor::_internal_av_input_channel() const {
  const ::f1x::aasdk::proto::data::AVInputChannel* p = _impl_.av_input_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::AVInputChannel&>(
      ::f1x::aasdk::proto::data::_AVInputChannel_default_instance_);
}
inline const ::f1x::aasdk::proto::data::AVInputChannel& ChannelDescriptor::av_input_channel() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.av_input_channel)
  return _internal_av_input_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_av_input_channel(
    ::f1x::aasdk::proto::data::AVInputChannel* av_input_channel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.av_input_channel_);
  }
  _impl_.av_input_channel_ = av_input_channel;
  if (av_input_channel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.av_input_channel)
}
inline ::f1x::aasdk::proto::data::AVInputChannel* ChannelDescriptor::release_av_input_channel() {
  
  ::f1x::aasdk::proto::data::AVInputChannel* temp = _impl_.av_input_channel_;
  _impl_.av_input_channel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::AVInputChannel* ChannelDescriptor::unsafe_arena_release_av_input_channel() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.ChannelDescriptor.av_input_channel)
  
  ::f1x::aasdk::proto::data::AVInputChannel* temp = _impl_.av_input_channel_;
  _impl_.av_input_channel_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::AVInputChannel* ChannelDescriptor::_internal_mutable_av_input_channel() {
  
  if (_impl_.av_input_channel_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::AVInputChannel>(GetArenaForAllocation());
    _impl_.av_input_channel_ = p;
  }
  return _impl_.av_input_channel_;
}
inline ::f1x::aasdk::proto::data::AVInputChannel* ChannelDescriptor::mutable_av_input_channel() {
  ::f1x::aasdk::proto::data::AVInputChannel* _msg = _internal_mutable_av_input_channel();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.ChannelDescriptor.av_input_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_av_input_channel(::f1x::aasdk::proto::data::AVInputChannel* av_input_channel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.av_input_channel_);
  }
  if (av_input_channel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(av_input_channel));
    if (message_arena != submessage_arena) {
      av_input_channel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, av_input_channel, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.av_input_channel_ = av_input_channel;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.av_input_channel)
}

// .f1x.aasdk.proto.data.BluetoothChannel bluetooth_channel = 6;
inline bool ChannelDescriptor::_internal_has_bluetooth_channel() const {
  return this != internal_default_instance() && _impl_.bluetooth_channel_ != nullptr;
}
inline bool ChannelDescriptor::has_bluetooth_channel() const {
  return _internal_has_bluetooth_channel();
}
inline const ::f1x::aasdk::proto::data::BluetoothChannel& ChannelDescriptor::_internal_bluetooth_channel() const {
  const ::f1x::aasdk::proto::data::BluetoothChannel* p = _impl_.bluetooth_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::BluetoothChannel&>(
      ::f1x::aasdk::proto::data::_BluetoothChannel_default_instance_);
}
inline const ::f1x::aasdk::proto::data::BluetoothChannel& ChannelDescriptor::bluetooth_channel() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
  return _internal_bluetooth_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_bluetooth_channel(
    ::f1x::aasdk::proto::data::BluetoothChannel* bluetooth_channel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bluetooth_channel_);
  }
  _impl_.bluetooth_channel_ = bluetooth_channel;
  if (bluetooth_channel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
}
inline ::f1x::aasdk::proto::data::BluetoothChannel* ChannelDescriptor::release_bluetooth_channel() {
  
  ::f1x::aasdk::proto::data::BluetoothChannel* temp = _impl_.bluetooth_channel_;
  _impl_.bluetooth_channel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::BluetoothChannel* ChannelDescriptor::unsafe_arena_release_bluetooth_channel() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
  
  ::f1x::aasdk::proto::data::BluetoothChannel* temp = _impl_.bluetooth_channel_;
  _impl_.bluetooth_channel_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::BluetoothChannel* ChannelDescriptor::_internal_mutable_bluetooth_channel() {
  
  if (_impl_.bluetooth_channel_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::BluetoothChannel>(GetArenaForAllocation());
    _impl_.bluetooth_channel_ = p;
  }
  return _impl_.bluetooth_channel_;
}
inline ::f1x::aasdk::proto::data::BluetoothChannel* ChannelDescriptor::mutable_bluetooth_channel() {
  ::f1x::aasdk::proto::data::BluetoothChannel* _msg = _internal_mutable_bluetooth_channel();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_bluetooth_channel(::f1x::aasdk::proto::data::BluetoothChannel* bluetooth_channel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bluetooth_channel_);
  }
  if (bluetooth_channel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(bluetooth_channel));
    if (message_arena != submessage_arena) {
      bluetooth_channel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bluetooth_channel, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.bluetooth_channel_ = bluetooth_channel;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.bluetooth_channel)
}

// .f1x.aasdk.proto.data.NavigationChannel navigation_channel = 8;
inline bool ChannelDescriptor::_internal_has_navigation_channel() const {
  return this != internal_default_instance() && _impl_.navigation_channel_ != nullptr;
}
inline bool ChannelDescriptor::has_navigation_channel() const {
  return _internal_has_navigation_channel();
}
inline const ::f1x::aasdk::proto::data::NavigationChannel& ChannelDescriptor::_internal_navigation_channel() const {
  const ::f1x::aasdk::proto::data::NavigationChannel* p = _impl_.navigation_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::NavigationChannel&>(
      ::f1x::aasdk::proto::data::_NavigationChannel_default_instance_);
}
inline const ::f1x::aasdk::proto::data::NavigationChannel& ChannelDescriptor::navigation_channel() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.navigation_channel)
  return _internal_navigation_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_navigation_channel(
    ::f1x::aasdk::proto::data::NavigationChannel* navigation_channel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.navigation_channel_);
  }
  _impl_.navigation_channel_ = navigation_channel;
  if (navigation_channel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.navigation_channel)
}
inline ::f1x::aasdk::proto::data::NavigationChannel* ChannelDescriptor::release_navigation_channel() {
  
  ::f1x::aasdk::proto::data::NavigationChannel* temp = _impl_.navigation_channel_;
  _impl_.navigation_channel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::NavigationChannel* ChannelDescriptor::unsafe_arena_release_navigation_channel() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.ChannelDescriptor.navigation_channel)
  
  ::f1x::aasdk::proto::data::NavigationChannel* temp = _impl_.navigation_channel_;
  _impl_.navigation_channel_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::NavigationChannel* ChannelDescriptor::_internal_mutable_navigation_channel() {
  
  if (_impl_.navigation_channel_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::NavigationChannel>(GetArenaForAllocation());
    _impl_.navigation_channel_ = p;
  }
  return _impl_.navigation_channel_;
}
inline ::f1x::aasdk::proto::data::NavigationChannel* ChannelDescriptor::mutable_navigation_channel() {
  ::f1x::aasdk::proto::data::NavigationChannel* _msg = _internal_mutable_navigation_channel();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.ChannelDescriptor.navigation_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_navigation_channel(::f1x::aasdk::proto::data::NavigationChannel* navigation_channel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.navigation_channel_);
  }
  if (navigation_channel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(navigation_channel));
    if (message_arena != submessage_arena) {
      navigation_channel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, navigation_channel, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.navigation_channel_ = navigation_channel;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.navigation_channel)
}

// .f1x.aasdk.proto.data.VendorExtensionChannel vendor_extension_channel = 12;
inline bool ChannelDescriptor::_internal_has_vendor_extension_channel() const {
  return this != internal_default_instance() && _impl_.vendor_extension_channel_ != nullptr;
}
inline bool ChannelDescriptor::has_vendor_extension_channel() const {
  return _internal_has_vendor_extension_channel();
}
inline const ::f1x::aasdk::proto::data::VendorExtensionChannel& ChannelDescriptor::_internal_vendor_extension_channel() const {
  const ::f1x::aasdk::proto::data::VendorExtensionChannel* p = _impl_.vendor_extension_channel_;
  return p != nullptr ? *p : reinterpret_cast<const ::f1x::aasdk::proto::data::VendorExtensionChannel&>(
      ::f1x::aasdk::proto::data::_VendorExtensionChannel_default_instance_);
}
inline const ::f1x::aasdk::proto::data::VendorExtensionChannel& ChannelDescriptor::vendor_extension_channel() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
  return _internal_vendor_extension_channel();
}
inline void ChannelDescriptor::unsafe_arena_set_allocated_vendor_extension_channel(
    ::f1x::aasdk::proto::data::VendorExtensionChannel* vendor_extension_channel) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.vendor_extension_channel_);
  }
  _impl_.vendor_extension_channel_ = vendor_extension_channel;
  if (vendor_extension_channel) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
}
inline ::f1x::aasdk::proto::data::VendorExtensionChannel* ChannelDescriptor::release_vendor_extension_channel() {
  
  ::f1x::aasdk::proto::data::VendorExtensionChannel* temp = _impl_.vendor_extension_channel_;
  _impl_.vendor_extension_channel_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::f1x::aasdk::proto::data::VendorExtensionChannel* ChannelDescriptor::unsafe_arena_release_vendor_extension_channel() {
  // @@protoc_insertion_point(field_release:f1x.aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
  
  ::f1x::aasdk::proto::data::VendorExtensionChannel* temp = _impl_.vendor_extension_channel_;
  _impl_.vendor_extension_channel_ = nullptr;
  return temp;
}
inline ::f1x::aasdk::proto::data::VendorExtensionChannel* ChannelDescriptor::_internal_mutable_vendor_extension_channel() {
  
  if (_impl_.vendor_extension_channel_ == nullptr) {
    auto* p = CreateMaybeMessage<::f1x::aasdk::proto::data::VendorExtensionChannel>(GetArenaForAllocation());
    _impl_.vendor_extension_channel_ = p;
  }
  return _impl_.vendor_extension_channel_;
}
inline ::f1x::aasdk::proto::data::VendorExtensionChannel* ChannelDescriptor::mutable_vendor_extension_channel() {
  ::f1x::aasdk::proto::data::VendorExtensionChannel* _msg = _internal_mutable_vendor_extension_channel();
  // @@protoc_insertion_point(field_mutable:f1x.aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
  return _msg;
}
inline void ChannelDescriptor::set_allocated_vendor_extension_channel(::f1x::aasdk::proto::data::VendorExtensionChannel* vendor_extension_channel) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.vendor_extension_channel_);
  }
  if (vendor_extension_channel) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vendor_extension_channel));
    if (message_arena != submessage_arena) {
      vendor_extension_channel = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vendor_extension_channel, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.vendor_extension_channel_ = vendor_extension_channel;
  // @@protoc_insertion_point(field_set_allocated:f1x.aasdk.proto.data.ChannelDescriptor.vendor_extension_channel)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ChannelDescriptorData_2eproto
