// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GPSLocationData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_GPSLocationData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_GPSLocationData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_GPSLocationData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_GPSLocationData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GPSLocationData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class GPSLocation;
struct GPSLocationDefaultTypeInternal;
extern GPSLocationDefaultTypeInternal _GPSLocation_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::GPSLocation* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::GPSLocation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class GPSLocation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.GPSLocation) */ {
 public:
  inline GPSLocation() : GPSLocation(nullptr) {}
  ~GPSLocation() override;
  explicit PROTOBUF_CONSTEXPR GPSLocation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GPSLocation(const GPSLocation& from);
  GPSLocation(GPSLocation&& from) noexcept
    : GPSLocation() {
    *this = ::std::move(from);
  }

  inline GPSLocation& operator=(const GPSLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline GPSLocation& operator=(GPSLocation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GPSLocation& default_instance() {
    return *internal_default_instance();
  }
  static inline const GPSLocation* internal_default_instance() {
    return reinterpret_cast<const GPSLocation*>(
               &_GPSLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GPSLocation& a, GPSLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(GPSLocation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GPSLocation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GPSLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GPSLocation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GPSLocation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GPSLocation& from) {
    GPSLocation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GPSLocation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.GPSLocation";
  }
  protected:
  explicit GPSLocation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 1,
    kLatitudeFieldNumber = 2,
    kLongitudeFieldNumber = 3,
    kAccuracyFieldNumber = 4,
    kAltitudeFieldNumber = 5,
    kSpeedFieldNumber = 6,
    kBearingFieldNumber = 7,
  };
  // uint64 timestamp = 1;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // int32 latitude = 2;
  void clear_latitude();
  int32_t latitude() const;
  void set_latitude(int32_t value);
  private:
  int32_t _internal_latitude() const;
  void _internal_set_latitude(int32_t value);
  public:

  // int32 longitude = 3;
  void clear_longitude();
  int32_t longitude() const;
  void set_longitude(int32_t value);
  private:
  int32_t _internal_longitude() const;
  void _internal_set_longitude(int32_t value);
  public:

  // uint32 accuracy = 4;
  void clear_accuracy();
  uint32_t accuracy() const;
  void set_accuracy(uint32_t value);
  private:
  uint32_t _internal_accuracy() const;
  void _internal_set_accuracy(uint32_t value);
  public:

  // int32 altitude = 5;
  void clear_altitude();
  int32_t altitude() const;
  void set_altitude(int32_t value);
  private:
  int32_t _internal_altitude() const;
  void _internal_set_altitude(int32_t value);
  public:

  // int32 speed = 6;
  void clear_speed();
  int32_t speed() const;
  void set_speed(int32_t value);
  private:
  int32_t _internal_speed() const;
  void _internal_set_speed(int32_t value);
  public:

  // int32 bearing = 7;
  void clear_bearing();
  int32_t bearing() const;
  void set_bearing(int32_t value);
  private:
  int32_t _internal_bearing() const;
  void _internal_set_bearing(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.GPSLocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t timestamp_;
    int32_t latitude_;
    int32_t longitude_;
    uint32_t accuracy_;
    int32_t altitude_;
    int32_t speed_;
    int32_t bearing_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GPSLocationData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GPSLocation

// uint64 timestamp = 1;
inline void GPSLocation::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t GPSLocation::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t GPSLocation::timestamp() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.GPSLocation.timestamp)
  return _internal_timestamp();
}
inline void GPSLocation::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void GPSLocation::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.GPSLocation.timestamp)
}

// int32 latitude = 2;
inline void GPSLocation::clear_latitude() {
  _impl_.latitude_ = 0;
}
inline int32_t GPSLocation::_internal_latitude() const {
  return _impl_.latitude_;
}
inline int32_t GPSLocation::latitude() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.GPSLocation.latitude)
  return _internal_latitude();
}
inline void GPSLocation::_internal_set_latitude(int32_t value) {
  
  _impl_.latitude_ = value;
}
inline void GPSLocation::set_latitude(int32_t value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.GPSLocation.latitude)
}

// int32 longitude = 3;
inline void GPSLocation::clear_longitude() {
  _impl_.longitude_ = 0;
}
inline int32_t GPSLocation::_internal_longitude() const {
  return _impl_.longitude_;
}
inline int32_t GPSLocation::longitude() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.GPSLocation.longitude)
  return _internal_longitude();
}
inline void GPSLocation::_internal_set_longitude(int32_t value) {
  
  _impl_.longitude_ = value;
}
inline void GPSLocation::set_longitude(int32_t value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.GPSLocation.longitude)
}

// uint32 accuracy = 4;
inline void GPSLocation::clear_accuracy() {
  _impl_.accuracy_ = 0u;
}
inline uint32_t GPSLocation::_internal_accuracy() const {
  return _impl_.accuracy_;
}
inline uint32_t GPSLocation::accuracy() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.GPSLocation.accuracy)
  return _internal_accuracy();
}
inline void GPSLocation::_internal_set_accuracy(uint32_t value) {
  
  _impl_.accuracy_ = value;
}
inline void GPSLocation::set_accuracy(uint32_t value) {
  _internal_set_accuracy(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.GPSLocation.accuracy)
}

// int32 altitude = 5;
inline void GPSLocation::clear_altitude() {
  _impl_.altitude_ = 0;
}
inline int32_t GPSLocation::_internal_altitude() const {
  return _impl_.altitude_;
}
inline int32_t GPSLocation::altitude() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.GPSLocation.altitude)
  return _internal_altitude();
}
inline void GPSLocation::_internal_set_altitude(int32_t value) {
  
  _impl_.altitude_ = value;
}
inline void GPSLocation::set_altitude(int32_t value) {
  _internal_set_altitude(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.GPSLocation.altitude)
}

// int32 speed = 6;
inline void GPSLocation::clear_speed() {
  _impl_.speed_ = 0;
}
inline int32_t GPSLocation::_internal_speed() const {
  return _impl_.speed_;
}
inline int32_t GPSLocation::speed() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.GPSLocation.speed)
  return _internal_speed();
}
inline void GPSLocation::_internal_set_speed(int32_t value) {
  
  _impl_.speed_ = value;
}
inline void GPSLocation::set_speed(int32_t value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.GPSLocation.speed)
}

// int32 bearing = 7;
inline void GPSLocation::clear_bearing() {
  _impl_.bearing_ = 0;
}
inline int32_t GPSLocation::_internal_bearing() const {
  return _impl_.bearing_;
}
inline int32_t GPSLocation::bearing() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.GPSLocation.bearing)
  return _internal_bearing();
}
inline void GPSLocation::_internal_set_bearing(int32_t value) {
  
  _impl_.bearing_ = value;
}
inline void GPSLocation::set_bearing(int32_t value) {
  _internal_set_bearing(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.GPSLocation.bearing)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_GPSLocationData_2eproto
