// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HVACData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_HVACData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_HVACData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_HVACData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_HVACData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_HVACData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class HVAC;
struct HVACDefaultTypeInternal;
extern HVACDefaultTypeInternal _HVAC_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::HVAC* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::HVAC>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class HVAC final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.HVAC) */ {
 public:
  inline HVAC() : HVAC(nullptr) {}
  ~HVAC() override;
  explicit PROTOBUF_CONSTEXPR HVAC(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HVAC(const HVAC& from);
  HVAC(HVAC&& from) noexcept
    : HVAC() {
    *this = ::std::move(from);
  }

  inline HVAC& operator=(const HVAC& from) {
    CopyFrom(from);
    return *this;
  }
  inline HVAC& operator=(HVAC&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HVAC& default_instance() {
    return *internal_default_instance();
  }
  static inline const HVAC* internal_default_instance() {
    return reinterpret_cast<const HVAC*>(
               &_HVAC_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HVAC& a, HVAC& b) {
    a.Swap(&b);
  }
  inline void Swap(HVAC* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HVAC* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HVAC* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HVAC>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HVAC& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HVAC& from) {
    HVAC::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HVAC* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.HVAC";
  }
  protected:
  explicit HVAC(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetTemperatureFieldNumber = 1,
    kCurrentTemperatureFieldNumber = 2,
  };
  // int32 target_temperature = 1;
  void clear_target_temperature();
  int32_t target_temperature() const;
  void set_target_temperature(int32_t value);
  private:
  int32_t _internal_target_temperature() const;
  void _internal_set_target_temperature(int32_t value);
  public:

  // int32 current_temperature = 2;
  void clear_current_temperature();
  int32_t current_temperature() const;
  void set_current_temperature(int32_t value);
  private:
  int32_t _internal_current_temperature() const;
  void _internal_set_current_temperature(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.HVAC)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t target_temperature_;
    int32_t current_temperature_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_HVACData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HVAC

// int32 target_temperature = 1;
inline void HVAC::clear_target_temperature() {
  _impl_.target_temperature_ = 0;
}
inline int32_t HVAC::_internal_target_temperature() const {
  return _impl_.target_temperature_;
}
inline int32_t HVAC::target_temperature() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.HVAC.target_temperature)
  return _internal_target_temperature();
}
inline void HVAC::_internal_set_target_temperature(int32_t value) {
  
  _impl_.target_temperature_ = value;
}
inline void HVAC::set_target_temperature(int32_t value) {
  _internal_set_target_temperature(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.HVAC.target_temperature)
}

// int32 current_temperature = 2;
inline void HVAC::clear_current_temperature() {
  _impl_.current_temperature_ = 0;
}
inline int32_t HVAC::_internal_current_temperature() const {
  return _impl_.current_temperature_;
}
inline int32_t HVAC::current_temperature() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.HVAC.current_temperature)
  return _internal_current_temperature();
}
inline void HVAC::_internal_set_current_temperature(int32_t value) {
  
  _impl_.current_temperature_ = value;
}
inline void HVAC::set_current_temperature(int32_t value) {
  _internal_set_current_temperature(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.HVAC.current_temperature)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_HVACData_2eproto
