// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NavigationImageOptionsData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_NavigationImageOptionsData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_NavigationImageOptionsData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_NavigationImageOptionsData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_NavigationImageOptionsData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NavigationImageOptionsData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class NavigationImageOptions;
struct NavigationImageOptionsDefaultTypeInternal;
extern NavigationImageOptionsDefaultTypeInternal _NavigationImageOptions_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::NavigationImageOptions* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::NavigationImageOptions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class NavigationImageOptions final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.NavigationImageOptions) */ {
 public:
  inline NavigationImageOptions() : NavigationImageOptions(nullptr) {}
  ~NavigationImageOptions() override;
  explicit PROTOBUF_CONSTEXPR NavigationImageOptions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NavigationImageOptions(const NavigationImageOptions& from);
  NavigationImageOptions(NavigationImageOptions&& from) noexcept
    : NavigationImageOptions() {
    *this = ::std::move(from);
  }

  inline NavigationImageOptions& operator=(const NavigationImageOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline NavigationImageOptions& operator=(NavigationImageOptions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NavigationImageOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const NavigationImageOptions* internal_default_instance() {
    return reinterpret_cast<const NavigationImageOptions*>(
               &_NavigationImageOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NavigationImageOptions& a, NavigationImageOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(NavigationImageOptions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NavigationImageOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NavigationImageOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NavigationImageOptions>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NavigationImageOptions& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NavigationImageOptions& from) {
    NavigationImageOptions::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NavigationImageOptions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.NavigationImageOptions";
  }
  protected:
  explicit NavigationImageOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
    kColourDepthBitsFieldNumber = 3,
  };
  // int32 width = 1;
  void clear_width();
  int32_t width() const;
  void set_width(int32_t value);
  private:
  int32_t _internal_width() const;
  void _internal_set_width(int32_t value);
  public:

  // int32 height = 2;
  void clear_height();
  int32_t height() const;
  void set_height(int32_t value);
  private:
  int32_t _internal_height() const;
  void _internal_set_height(int32_t value);
  public:

  // int32 colour_depth_bits = 3;
  void clear_colour_depth_bits();
  int32_t colour_depth_bits() const;
  void set_colour_depth_bits(int32_t value);
  private:
  int32_t _internal_colour_depth_bits() const;
  void _internal_set_colour_depth_bits(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.NavigationImageOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t width_;
    int32_t height_;
    int32_t colour_depth_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_NavigationImageOptionsData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NavigationImageOptions

// int32 width = 1;
inline void NavigationImageOptions::clear_width() {
  _impl_.width_ = 0;
}
inline int32_t NavigationImageOptions::_internal_width() const {
  return _impl_.width_;
}
inline int32_t NavigationImageOptions::width() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.NavigationImageOptions.width)
  return _internal_width();
}
inline void NavigationImageOptions::_internal_set_width(int32_t value) {
  
  _impl_.width_ = value;
}
inline void NavigationImageOptions::set_width(int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.NavigationImageOptions.width)
}

// int32 height = 2;
inline void NavigationImageOptions::clear_height() {
  _impl_.height_ = 0;
}
inline int32_t NavigationImageOptions::_internal_height() const {
  return _impl_.height_;
}
inline int32_t NavigationImageOptions::height() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.NavigationImageOptions.height)
  return _internal_height();
}
inline void NavigationImageOptions::_internal_set_height(int32_t value) {
  
  _impl_.height_ = value;
}
inline void NavigationImageOptions::set_height(int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.NavigationImageOptions.height)
}

// int32 colour_depth_bits = 3;
inline void NavigationImageOptions::clear_colour_depth_bits() {
  _impl_.colour_depth_bits_ = 0;
}
inline int32_t NavigationImageOptions::_internal_colour_depth_bits() const {
  return _impl_.colour_depth_bits_;
}
inline int32_t NavigationImageOptions::colour_depth_bits() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.NavigationImageOptions.colour_depth_bits)
  return _internal_colour_depth_bits();
}
inline void NavigationImageOptions::_internal_set_colour_depth_bits(int32_t value) {
  
  _impl_.colour_depth_bits_ = value;
}
inline void NavigationImageOptions::set_colour_depth_bits(int32_t value) {
  _internal_set_colour_depth_bits(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.NavigationImageOptions.colour_depth_bits)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_NavigationImageOptionsData_2eproto
