// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShutdownReasonEnum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ShutdownReasonEnum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ShutdownReasonEnum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ShutdownReasonEnum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ShutdownReasonEnum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ShutdownReasonEnum_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace enums {
class ShutdownReason;
struct ShutdownReasonDefaultTypeInternal;
extern ShutdownReasonDefaultTypeInternal _ShutdownReason_default_instance_;
}  // namespace enums
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::enums::ShutdownReason* Arena::CreateMaybeMessage<::f1x::aasdk::proto::enums::ShutdownReason>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace enums {

enum ShutdownReason_Enum : int {
  ShutdownReason_Enum_NONE = 0,
  ShutdownReason_Enum_QUIT = 1,
  ShutdownReason_Enum_ShutdownReason_Enum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ShutdownReason_Enum_ShutdownReason_Enum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ShutdownReason_Enum_IsValid(int value);
constexpr ShutdownReason_Enum ShutdownReason_Enum_Enum_MIN = ShutdownReason_Enum_NONE;
constexpr ShutdownReason_Enum ShutdownReason_Enum_Enum_MAX = ShutdownReason_Enum_QUIT;
constexpr int ShutdownReason_Enum_Enum_ARRAYSIZE = ShutdownReason_Enum_Enum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ShutdownReason_Enum_descriptor();
template<typename T>
inline const std::string& ShutdownReason_Enum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ShutdownReason_Enum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ShutdownReason_Enum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ShutdownReason_Enum_descriptor(), enum_t_value);
}
inline bool ShutdownReason_Enum_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ShutdownReason_Enum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ShutdownReason_Enum>(
    ShutdownReason_Enum_descriptor(), name, value);
}
// ===================================================================

class ShutdownReason final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.enums.ShutdownReason) */ {
 public:
  inline ShutdownReason() : ShutdownReason(nullptr) {}
  explicit PROTOBUF_CONSTEXPR ShutdownReason(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShutdownReason(const ShutdownReason& from);
  ShutdownReason(ShutdownReason&& from) noexcept
    : ShutdownReason() {
    *this = ::std::move(from);
  }

  inline ShutdownReason& operator=(const ShutdownReason& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShutdownReason& operator=(ShutdownReason&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShutdownReason& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShutdownReason* internal_default_instance() {
    return reinterpret_cast<const ShutdownReason*>(
               &_ShutdownReason_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ShutdownReason& a, ShutdownReason& b) {
    a.Swap(&b);
  }
  inline void Swap(ShutdownReason* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShutdownReason* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShutdownReason* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShutdownReason>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const ShutdownReason& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const ShutdownReason& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.enums.ShutdownReason";
  }
  protected:
  explicit ShutdownReason(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ShutdownReason_Enum Enum;
  static constexpr Enum NONE =
    ShutdownReason_Enum_NONE;
  static constexpr Enum QUIT =
    ShutdownReason_Enum_QUIT;
  static inline bool Enum_IsValid(int value) {
    return ShutdownReason_Enum_IsValid(value);
  }
  static constexpr Enum Enum_MIN =
    ShutdownReason_Enum_Enum_MIN;
  static constexpr Enum Enum_MAX =
    ShutdownReason_Enum_Enum_MAX;
  static constexpr int Enum_ARRAYSIZE =
    ShutdownReason_Enum_Enum_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Enum_descriptor() {
    return ShutdownReason_Enum_descriptor();
  }
  template<typename T>
  static inline const std::string& Enum_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Enum>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Enum_Name.");
    return ShutdownReason_Enum_Name(enum_t_value);
  }
  static inline bool Enum_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Enum* value) {
    return ShutdownReason_Enum_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.enums.ShutdownReason)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_ShutdownReasonEnum_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ShutdownReason

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace enums
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::f1x::aasdk::proto::enums::ShutdownReason_Enum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::f1x::aasdk::proto::enums::ShutdownReason_Enum>() {
  return ::f1x::aasdk::proto::enums::ShutdownReason_Enum_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ShutdownReasonEnum_2eproto
