// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TouchLocationData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TouchLocationData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TouchLocationData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TouchLocationData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TouchLocationData_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TouchLocationData_2eproto;
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {
class TouchLocation;
struct TouchLocationDefaultTypeInternal;
extern TouchLocationDefaultTypeInternal _TouchLocation_default_instance_;
}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x
PROTOBUF_NAMESPACE_OPEN
template<> ::f1x::aasdk::proto::data::TouchLocation* Arena::CreateMaybeMessage<::f1x::aasdk::proto::data::TouchLocation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace f1x {
namespace aasdk {
namespace proto {
namespace data {

// ===================================================================

class TouchLocation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:f1x.aasdk.proto.data.TouchLocation) */ {
 public:
  inline TouchLocation() : TouchLocation(nullptr) {}
  ~TouchLocation() override;
  explicit PROTOBUF_CONSTEXPR TouchLocation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TouchLocation(const TouchLocation& from);
  TouchLocation(TouchLocation&& from) noexcept
    : TouchLocation() {
    *this = ::std::move(from);
  }

  inline TouchLocation& operator=(const TouchLocation& from) {
    CopyFrom(from);
    return *this;
  }
  inline TouchLocation& operator=(TouchLocation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TouchLocation& default_instance() {
    return *internal_default_instance();
  }
  static inline const TouchLocation* internal_default_instance() {
    return reinterpret_cast<const TouchLocation*>(
               &_TouchLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TouchLocation& a, TouchLocation& b) {
    a.Swap(&b);
  }
  inline void Swap(TouchLocation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TouchLocation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TouchLocation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TouchLocation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TouchLocation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TouchLocation& from) {
    TouchLocation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TouchLocation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "f1x.aasdk.proto.data.TouchLocation";
  }
  protected:
  explicit TouchLocation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kPointerIdFieldNumber = 3,
  };
  // uint32 x = 1;
  void clear_x();
  uint32_t x() const;
  void set_x(uint32_t value);
  private:
  uint32_t _internal_x() const;
  void _internal_set_x(uint32_t value);
  public:

  // uint32 y = 2;
  void clear_y();
  uint32_t y() const;
  void set_y(uint32_t value);
  private:
  uint32_t _internal_y() const;
  void _internal_set_y(uint32_t value);
  public:

  // uint32 pointer_id = 3;
  void clear_pointer_id();
  uint32_t pointer_id() const;
  void set_pointer_id(uint32_t value);
  private:
  uint32_t _internal_pointer_id() const;
  void _internal_set_pointer_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:f1x.aasdk.proto.data.TouchLocation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t x_;
    uint32_t y_;
    uint32_t pointer_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TouchLocationData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TouchLocation

// uint32 x = 1;
inline void TouchLocation::clear_x() {
  _impl_.x_ = 0u;
}
inline uint32_t TouchLocation::_internal_x() const {
  return _impl_.x_;
}
inline uint32_t TouchLocation::x() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.TouchLocation.x)
  return _internal_x();
}
inline void TouchLocation::_internal_set_x(uint32_t value) {
  
  _impl_.x_ = value;
}
inline void TouchLocation::set_x(uint32_t value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.TouchLocation.x)
}

// uint32 y = 2;
inline void TouchLocation::clear_y() {
  _impl_.y_ = 0u;
}
inline uint32_t TouchLocation::_internal_y() const {
  return _impl_.y_;
}
inline uint32_t TouchLocation::y() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.TouchLocation.y)
  return _internal_y();
}
inline void TouchLocation::_internal_set_y(uint32_t value) {
  
  _impl_.y_ = value;
}
inline void TouchLocation::set_y(uint32_t value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.TouchLocation.y)
}

// uint32 pointer_id = 3;
inline void TouchLocation::clear_pointer_id() {
  _impl_.pointer_id_ = 0u;
}
inline uint32_t TouchLocation::_internal_pointer_id() const {
  return _impl_.pointer_id_;
}
inline uint32_t TouchLocation::pointer_id() const {
  // @@protoc_insertion_point(field_get:f1x.aasdk.proto.data.TouchLocation.pointer_id)
  return _internal_pointer_id();
}
inline void TouchLocation::_internal_set_pointer_id(uint32_t value) {
  
  _impl_.pointer_id_ = value;
}
inline void TouchLocation::set_pointer_id(uint32_t value) {
  _internal_set_pointer_id(value);
  // @@protoc_insertion_point(field_set:f1x.aasdk.proto.data.TouchLocation.pointer_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace data
}  // namespace proto
}  // namespace aasdk
}  // namespace f1x

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TouchLocationData_2eproto
